### ISSUE TITLE
Avoid Rate Limiting By Using An atom.io Token

### ISSUE THREAD

**Issue by joefitzgerald** [atom/ci#39]
https://travis-ci.org/joefitzgerald/autocomplete-go/jobs/116517199

> Unable to download https://www.atom.io/api/packages/environment/versions/1.1.1/tarball: 403 Forbidden API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

This can be avoided by using a token for atom.io and avoiding anonymous use of the API.

/cc @thedaniel

**Comment by elierotenberg** [comment]
How do you use a token? I tried setting it using `apm login` and `export GITHUB_API_TOKEN=XXX`, neither seem to work.

**Comment by joefitzgerald** [comment]
Reopening this because #40 did not fix it.

**Comment by jwdomingo** [comment]
@elierotenberg, I generated a new **`atom.io`** token from my [GitHub token settings](https://github.com/settings/tokens). Then I ran: `apm login`

Instead of using the API token provided on the Atom account page (the atom token starts with an underscore..) I used the GitHub token I just generated and was able to download again.

Hope that helps!

**Comment by elierotenberg** [comment]
Thanks @jwdomingo, I tried this but unfortunately it didn't work in my case either. I may have another problem. I'll update this thread if I find anything helpful...

**Comment by joefitzgerald** [comment]
Per https://github.com/atom/apm/pull/526, this is now resolved via a change in atom.io.
