### ISSUE TITLE
build script is failing for linus on travis

### ISSUE THREAD

**Issue by BugDiver** [atom/ci#42]
i'm using the [build package](https://github.com/atom/ci/blob/master/build-package.sh) in my package.
i have copied the [travis script](https://github.com/atom/ci/blob/master/.travis.yml) in my proj.
but the [build](https://travis-ci.org/BugDiver/gauge-atom/jobs/138488630) is failing on linux.

**Comment by Arcanemagus** [comment]
Just because your build is failing doesn't mean the build script here is at fault 😛.

In this case you [specified](https://github.com/BugDiver/gauge-atom/blob/4f1352e60b4f1e1fdfd8366e3bd3ea19e8109859/spec/gaugeUtil-spec.coffee#L3) to load `'../lib/utils/GaugeUtil'` in your test script, when the file is `gaugeUtil.coffee` (note the capitalization difference).

**Comment by mnquintana** [comment]
Thanks @Arcanemagus! I'm gonna close this out.

**Comment by BugDiver** [comment]
Agreed. not saying that build script has fault. ```GaugeUtil``` is exported as module from ```gaugeUtil.coffee```.
A quick question is how it's passing on [Darwin](https://travis-ci.org/BugDiver/gauge-atom/jobs/138493335).

**Comment by Arcanemagus** [comment]
I'm betting that the OS X install that Travis-CI is using is installed on a case-insensitive file system. This is pretty common for OS X installs as many applications _assume_ that... and will break otherwise (for similar issues to what you just ran into).
