### ISSUE TITLE
Build script broken with ESLint 3.x?

### ISSUE THREAD

**Issue by morkro** [atom/ci#44]
Hello,

I am using the [`build-package.sh`](https://github.com/atom/ci/blob/master/build-package.sh) and it has always worked great for my project, but since I've updated to [ESLint 3.x](https://github.com/eslint/eslint/releases/tag/v3.0.1) my build is [broken](https://travis-ci.org/morkro/atom-emoji-syntax/builds/142985005). 

The problem seems to be that the script uses the APM versions, which is Node `0.10.40`, but ESLint 3.x requires Node `>=4`.

Is there a way to fix or work around this?

**Comment by thomasjo** [comment]
This was fixed in https://github.com/atom/ci/pull/43. Try restarting your builds ♻️

**Comment by morkro** [comment]
Awesome, thanks!

**Comment by morkro** [comment]
Sorry to be noisy, but the issue [remains](https://travis-ci.org/morkro/atom-emoji-syntax/builds/142985005). :/

**Comment by thomasjo** [comment]
Oh, that specific issue won't be fixed by anything we can do here. If an npm package is listed as a dependency it will be installed using `apm` and not `npm`, and apm uses Node v.0.10.40 still.

If you want to use eslint v3 and above, then for the time being you'll have to deal with linting on your own. That means removing it as a dependency in your `package.json`, installing it into e.g. a `script` folder along with a custom `lint` script or some such.

On a side note, this shouldn't even work locally? What you are seeing is not specific to running stuff on Travis CI.

Furthermore, this will be fixed when https://github.com/atom/atom/pull/11897 🚢s.

**Comment by morkro** [comment]
Ah okay, got it. 

Locally I have always been linting with `npm` scripts like `eslint lib && eslint spec`. I didn't know there is an `apm` linting command available? 

Is there a rough estimate when [atom/atom#11897](https://github.com/atom/atom/pull/11897) will be merged? Either I just wait, or go back to ESLint 2.x.
